apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: prometheus 
  namespace: prometheus 
spec:
  interval: 5m0s
  chart: 
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: prometheus 
  version: '5.*'
