apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: '27.*'  # <- dopasuj wersję Prometheusa
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
