apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn
  namespace: monitoring
spec:
  secretName: longhorn-tls
  issuerRef:
    name: letsencrypt-http-prod
    kind: ClusterIssuer
  commonName: longhorn.homelab.kacperjarocki.dev
  dnsNames:
    - longhorn.homelab.kacperjarocki.dev
