apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.11.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  values:
    ingress:
      enabled: true
      host: longhorn.homelab.kacperjarocki.dev
      tls: true
      tlsSecret:  longhorn-tls
    # metrics:
    #   serviceMonitor:
    #     enabled: true
    #     namespace: monitoring
    #     labels:
    #       release: kube-prometheus-stack
