apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: '1.10.1'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  values:
    ingress:
      enabled: true
      host: longhorn.homelab.kacperjarocki.dev
      tls: true
      tlsSecret:  longhorn-tls
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: true
    metrics:
      serviceMonitor:
        enabled: true
        namespace: monitoring
        labels:
          release: kube-prometheus-stack
