apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-homelab-dev
  namespace: nextcloud 
spec:
  secretName: nextcloud-homelab-kacperjarocki-dev-tls   
  issuerRef:
    name: letsencrypt-http-prod
    kind: ClusterIssuer
  commonName: nextcloud.homelab.kacperjarocki.dev
  dnsNames:
    - nextcloud.homelab.kacperjarocki.dev
