apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: databases-secrets 
  namespace: nextcloud
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: databases-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: "databases-secrets"
        property: "postgres-user"
    - secretKey: db-password
      remoteRef:
        key: "databases-secrets"
        property: "postgres-pass"
    - secretKey: redis-password
      remoteRef:
        key: "databases-secrets"
        property: "redis-pass"
