apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: '6.6.10'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http-prod
      hosts:
        - host: nextcloud.homelab.kacperjarocki.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - nextcloud.homelab.kacperjarocki.dev
          secretName: nextcloud-homelab-kacperjarocki-dev-tls

    nextcloud:
      host: nextcloud.homelab.kacperjarocki.dev
      trustedDomains:
        - nextcloud.homelab.kacperjarocki.dev
