apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud 
  namespace: nextcloud 
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud 
      version: '6.6.10'
      sourceRef:
        kind: HelmRepository
        name: nextcloud 
        namespace: nextcloud
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-http
      hosts:
        - nextcloud.homelab.kacperjarocki.dev
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - nextcloud.homelab.kacperjarocki.dev
          secretName: nextcloud-homelab-kacperjarocki-dev-tls
