apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kyverno
      version: "3.7.1"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno-system
      interval: 1h
  values:
    admissionController:
      replicas: 3
      metricsService:
        create: true
    backgroundController:
      replicas: 3
      metricsService:
        create: true
    cleanupController:
      replicas: 3
      metricsService:
        create: true
    reportsController:
      replicas: 3
      metricsService:
        create: true
