apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-kacperjarocki-dev
  namespace: default
spec:
  secretName: homelab-kacperjarocki-dev-tls
  issuerRef:
    name: letsencrypt-http-prod
    kind: ClusterIssuer
  commonName: "*.homelab.kacperjarocki.dev"
  dnsNames:
  - "homelab.kacperjarocki.dev"
  - "*.homelab.kacperjarocki.dev"
