apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dev.kacperjarocki@proton.me
    privateKeySecretRef:
      name: letsencrypt-dns-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            email: dev.kacperjarocki@proton.me
            apiTokenSecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - kacperjarocki.dev
