apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich
  namespace: immich
spec:
  secretName: immich-tls
  issuerRef:
    name: letsencrypt-http-prod
    kind: ClusterIssuer
  dnsNames:
    - immich.homelab.kacperjarocki.dev
