apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: '9.*'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    persistence:
      enabled: true
      size: 5Gi
    initChownData:
      enabled: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-server.monitoring.svc.cluster.local
            isDefault: true
