apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: '9.*'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-http
      hosts:
        - grafana.homelab.kacperjarocki.dev
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - grafana.homelab.kacperjarocki.dev
          secretName: homelab-kacperjarocki-dev-tls

    persistence:
      enabled: true
      size: 5Gi
    initChownData:
      enabled: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-server.monitoring.svc.cluster.local
            isDefault: true
