apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  dependsOn:
    - name:  longhorn-system
  interval: 1m
  path: ./infra/cloudNativePg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
