apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-metallb-config
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: network-metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infra/networking/metallbConfiguration
  prune: true
  wait: true
  timeout: 3m
  targetNamespace: networking
