apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http-prod
spec:
  acme:
    email: dev.kacperjarocki@proton.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http-key-prod
    solvers:
    - dns01:
        cloudflare:
          email: dev.kacperjarocki@proton.me
          apiTokenSecretRef:
           name: cloudflare-api-key
           key: api-key
      selector:
        dnsZones:
          - "kacperjarocki.dev"

