apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: '1.12.*' 
      sourceRef:
        kind: HelmRepository
        name: cert-manager 
        namespace: cert-manager
  values:
    crds:
      enabled: true
