apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: cert-manager 
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "cloudflare"         
      version: "v2"
      auth:
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "external-secrets-role"
          serviceAccountRef:
            name: external-secrets-sa
