apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault 
spec:
  interval: 5m
  chart:
    spec:
      chart: vault 
      version: '0.30.*' 
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
