apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metalpool 
  namespace: networking 
spec:
  addresses:
  - 10.20.30.50-10.20.30.200
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metalad
  namespace: networking
spec:
  ipAddressPools:
  - metalpool
