apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metalpool 
  namespace: networking 
spec:
  addresses:
  - 192.168.1.50-192.168.1.100
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metalad
  namespace: networking
spec:
  ipAddressPools:
  - metalpool
