apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docmost
  namespace: docmost
spec:
  interval: 15m
  chart:
    spec:
      chart: docmost
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: mycharts
        namespace: docmost
      interval: 1h
  values:
    ingress:
      enabled: true
      hosts:
        - host: docs.homelab.kacperjarocki.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: docmost-tls
          hosts:
            - docs.homelab.kacperjarocki.dev
