apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1h

  values:
    deploymentMode: SimpleScalable

    minio:
      enabled: false

    loki:
      auth_enabled: false

      commonConfig:
        replication_factor: 1

      storage:
        type: s3
        bucketNames:
          chunks: loki
          ruler: loki
          admin: loki
        s3:
          endpoint: https://rustfs.kacperjarocki.dev
          region: poland
          s3ForcePathStyle: true
          accessKeyId: loki
          secretAccessKey: ldwGaLxJymHkU3sBfV1T6q0C5XEhKoYrp82tuZWO

      schemaConfig:
        configs:
          - from: "2026-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      limits_config:
        retention_period: 168h
        allow_structured_metadata: true
        volume_enabled: true

    write:
      replicas: 3
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi

    backend:
      replicas: 3
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi

    read:
      replicas: 3


    memcached:
      enabled: false

    memcachedChunks:
      enabled: true
      replicas: 1
      resources:
        requests:
          memory: 4Gi
          cpu: 200m
        limits:
          memory: 4Gi
          cpu: 1

    memcachedResults:
      enabled: false

    memcachedIndexQueries:
      enabled: false

    memcachedIndexWrites:
      enabled: false

    gateway:
      enabled: true
      service:
        type: ClusterIP
