apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: alloy-config
  namespace: monitoring

configMapGenerator:
  - name: alloy
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
