apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alloy-config
  namespace: monitoring
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  configMapGenerator:
    - name: alloy
      files:
        - config.alloy
      options:
        disableNameSuffixHash: true
